# Generated by Django 2.1.11 on 2019-09-02 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('full_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Active'), (2, 'Terminate'), (3, 'Resign'), (4, 'Other Agent Status')], null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pria'), (2, 'Wanita'), (3, 'Other')], null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('religion', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Islam'), (2, 'Kristen'), (3, 'Katolik'), (4, 'Hindu'), (5, 'Buddha'), (6, 'Other Religion')], null=True)),
                ('marital_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Belum Menikah'), (2, 'Menikah'), (3, 'Cerai'), (4, 'Duda/Janda'), (5, 'Other Marital Status')], null=True)),
                ('id_number', models.CharField(blank=True, default='', max_length=255)),
                ('npwp_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ptkp_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Tidak Kawin'), (2, 'Kawin Tidak Punya Anak'), (3, 'Kawin Dengan Anak 1'), (4, 'Kawin Dengan Anak 2'), (5, 'Kawin Dengan Anak 3'), (6, 'Other PTKP')], null=True)),
                ('hire_date', models.DateField(blank=True, default=None, null=True)),
                ('terminate_date', models.DateField(blank=True, default=None, null=True)),
                ('aaji_number', models.CharField(blank=True, default='', max_length=255)),
                ('aaji_license_date', models.DateField(blank=True, default=None, null=True)),
                ('aaji_expired_date', models.DateField(blank=True, default=None, null=True)),
                ('license_phase', models.CharField(blank=True, default='', max_length=255)),
                ('contract_date', models.DateField(blank=True, default=None, null=True)),
                ('fast_date', models.DateField(blank=True, default=None, null=True)),
                ('origin_id', models.CharField(blank=True, default='', max_length=255)),
                ('first_login', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AgentProfile',
                'verbose_name_plural': 'Agent Profiles',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=255)),
                ('origin_id', models.CharField(max_length=255)),
                ('office_code', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branch',
            },
        ),
        migrations.CreateModel(
            name='UserBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('branch', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='agencies.Branch')),
                ('user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserBranch',
                'verbose_name_plural': 'User Branchs',
            },
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agencies.Branch'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userbranch',
            unique_together={('user', 'branch')},
        ),
    ]
